apiVersion: v1
kind: Service
metadata:
  name: metrics-app
  namespace: default
  labels:
    app: metrics-app
spec:
  selector:
    app: metrics-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
